import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import Control from "./Control";

export const metadata: Metadata = {
  title: "Web",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const res = await fetch("http://localhost:9999/topics");
  const result = await res.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">Web</Link>
        </h1>
        <ol>
          {result.map((item: { id: number; title: string }) => (
            <li key={item.id}>
              <Link href={`/read/${item.id}`}>{item.title}</Link>
            </li>
          ))}
        </ol>
        {children}
        <Control />
      </body>
    </html>
  );
}
